[package]
name = "benchmark"
version = "0.1.0"

[dependencies]
grpcio = { path = ".." }
grpcio-proto = { path = "../proto" }
futures = "0.1"
libc = "0.2"
grpcio-sys = { path = "../grpc-sys" }
rand = "0.3"
tokio-timer = "0.1"
clap = "2.23"

[[bin]]
name = "qps_worker"
path = "src/main.rs"
