[package]
name = "benchmark"
version = "0.1.0"
authors = ["Jay Lee <busyjaylee@gmail.com>"]

[dependencies]
grpc = { path = ".." }
grpc-proto = { path = "../proto" }
tokio-core = "0.1"
futures = "0.1"
futures-cpupool = "0.1"
libc = "0.2"
grpc-sys = { path = "../grpc-sys" }
rand = "0.3"
tokio-timer = "0.1"
clap = "2.23"
