dist: trusty
sudo: false
language: rust
cache:
  directories:
    - $HOME/.cargo
    - $HOME/.cache
    - $TRAVIS_BUILD_DIR/target
before_cache:
  - find $TRAVIS_BUILD_DIR/target/debug -maxdepth 1 -type f -delete
  - cargo clean -p grpcio-sys
os:
  - linux
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  include:
  - os: osx
    rust: stable
script:
  - if [[ $TRAVIS_RUST_VERSION == "nightly" ]]; then cargo install -f clippy && cargo clippy; fi
  - export RUSTFLAGS=-Dwarnings
  - export RUST_BACKTRACE=1
  - cargo build
  - cargo test --all
