# Travis is only used to test ARM64 Linux

dist: focal
sudo: false
language: rust
git:
  submodules: false

rust: stable

env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="--deny=warnings"
    - TEST_BIND=1

addons:
  apt:
    update: true
    packages:
      - libunwind-dev

jobs:
  include:
  - os: linux
    arch: arm64
    before_script:
      - scripts/reset-submodule.cmd
      - export GRPC_VERSION=1.33.1
      - export PATH="$PATH:$HOME/.cache/bin:$HOME/.cargo/bin"
      - GRPC_HEADER="$HOME/.cache/include/grpc/grpc.h"
      - if [[ ! -f "$GRPC_HEADER" ]] ; then
          (
            git clone --recurse-submodules -b v$GRPC_VERSION https://github.com/grpc/grpc &&
            cd grpc &&
            mkdir -p cmake/build &&
            cd cmake/build &&
            cmake -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=$HOME/.cache ../.. &&
            make -j &&
            make install &&
            cd ../..
          );
        fi
      - eval "$(gimme stable)"
      - export CPLUS_INCLUDE_PATH="$HOME/.cache/include"
      - export LD_LIBRARY_PATH="$HOME/.cache/lib"
      - export DYLD_LIBRARY_PATH="$HOME/.cache/lib"
      - export LIBRARY_PATH="$HOME/.cache/lib"
      - export PKG_CONFIG_PATH="$HOME/.cache/lib/pkgconfig"
    script:
      - GRPCIO_SYS_USE_PKG_CONFIG=1 RUSTFLAGS="-A unused-attributes" cargo test --all

  - os: linux
    arch: arm64
    before_script:
      - scripts/reset-submodule.cmd
      - export GRPC_VERSION=1.33.1
      - export PATH="$PATH:$HOME/.cache/bin:$HOME/.cargo/bin"
      - GRPC_HEADER="$HOME/.cache/include/grpc/grpc.h"
      - sudo apt-get update && sudo apt-get -y install libssl-dev
      - which cmake && cmake --version 
      - eval "$(gimme stable)"
      - export CPLUS_INCLUDE_PATH="$HOME/.cache/include"
      - export LD_LIBRARY_PATH="$HOME/.cache/lib"
      - export DYLD_LIBRARY_PATH="$HOME/.cache/lib"
      - export LIBRARY_PATH="$HOME/.cache/lib"
      - export PKG_CONFIG_PATH="$HOME/.cache/lib/pkgconfig"
    script:
      - if [[ $TRAVIS_OS_NAME == "linux" ]] && [[ $TRAVIS_RUST_VERSION == "stable" ]]; then
          rustup component add rustfmt && cargo fmt --all -- --check;
          env TEST_BIND=0 scripts/generate-bindings.sh && git diff --exit-code HEAD;
        fi
      - ./scripts/generate-bindings.sh
      - cargo build --no-default-features
      - cargo build --no-default-features --features protobuf-codec
      - cargo build --no-default-features --features prost-codec
      - cargo build
      - cargo test --all
      - cargo test --features "openssl" --all
      - cargo test --features "openssl-vendored" --all
