environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - git submodule -q update --init --recursive
  - choco install golang
  - choco install yasm
  - choco install protoc
  - rustc -V
  - cargo -V
    
build: false

test_script:
  - cargo build
  - cargo test --all
