[package]
name = "grpc"
version = "0.1.0"

[dependencies]
grpc-sys = { path = "grpc-sys", version = "0.1" }
libc = "0.2"
futures = "0.1"
protobuf = "1.2"
clippy = { version = "*", optional = true }

[workspace]
members = ["interop"]

[features]
default = []
dev = ["clippy"]

[dev-dependencies]
tokio-core = "0.1"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
grpc-proto = { path = "proto" }
