[package]
name = "grpc"
version = "0.1.0"

[dependencies]
grpc-sys = { path = "grpc-sys", version = "0.1" }
libc = "0.2"
futures = "0.1"
protobuf = { version = "1.2", optional = true }
clippy = { version = "*", optional = true }

[workspace]
members = ["proto", "interop", "benchmark", "compiler"]

[features]
default = ["protobuf-codec"]
dev = ["clippy"]
protobuf-codec = ["protobuf"]
static-link = ["grpc-sys/static-link"]

[dev-dependencies]
futures-cpupool = "0.1"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
grpc-proto = { path = "proto" }
