[package]
name = "grpc-compiler"
version = "0.1.0"
description = "gRPC compiler for grpc-rs"
license = "MIT/Apache-2.0"

workspace = ".."

[dependencies]
protobuf = "1.2"

[[bin]]
name = "grpc_rust_plugin"
