[package]
name = "compiler"
version = "0.1.0"
description = "gRPC compiler for grpc-rs"
license = "MIT/Apache-2.0"
authors = [
    "Stepan Koltsov <stepan.koltsov@gmail.com>",
    "Neil Shen <overvenus@gmail.com>"
]

[dependencies]
protobuf = "1.2"

[[bin]]
name = "protoc-gen-rust-grpc"
