[package]
name = "grpc-proto"
version = "0.1.0"
build = "build.rs"

[dependencies]
protobuf = "1.2"
futures = "0.1"
grpc = { path = ".." }

[build-dependencies]
protobuf = "1.2"
grpc-compiler = { path = "../compiler" }
