[package]
name = "grpcio-proto"
version = "0.1.0"
build = "build.rs"

[dependencies]
protobuf = "1.2"
futures = "0.1"
grpcio = { path = ".." }

[build-dependencies]
protobuf = "1.2"
grpcio-compiler = { path = "../compiler" }
