[package]
name = "interop"
version = "0.1.0"
authors = ["Jay Lee <busyjaylee@gmail.com>"]

[dependencies]
grpc = { path = ".." }
grpc-sys = { path = "../grpc-sys" }
grpc-proto = { path = "../proto" }
protobuf = "1.2"
futures = "0.1"
futures-cpupool = "0.1"
clap = "2.23"
clippy = { version = "*", optional = true }

[features]
default = []
dev = ["clippy"]
