[package]
name = "interop"
version = "0.1.0"

[dependencies]
grpcio = { path = ".." }
grpcio-sys = { path = "../grpc-sys" }
grpcio-proto = { path = "../proto" }
protobuf = "1.2"
futures = "0.1"
clap = "2.23"
clippy = { version = "*", optional = true }

[[bin]]
name = "interop_client"
path = "src/bin/client.rs"

[[bin]]
name = "interop_server"
path = "src/bin/server.rs"

[features]
default = []
dev = ["clippy"]
